name: build-assets

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Copy .env
        run: cp .env.example .env
      - name: Install dependencies
        run: |
          composer install --no-interaction
          npm install
      - name: Build assets
        run: npm run build
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: >
            Build assets
