name: run-tests

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: medtest1
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Copy .env
        run: cp .env.example .env
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Generate key
        run: php artisan key:generate
      - name: Run tests
        env:
          APP_URL: 'http://127.0.0.1:8000'
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          php artisan serve > /dev/null 2>&1 &
          php artisan test
